sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t pancutan/react-test -f ./client/Dockerfile.dev ./client

script: # Solo tests o cosas que devuelvan enteros al terminar
  # Para que el test no se quede loopenado. Que termine y arroje 0 u otra cosa
  # - docker run pancutan/react-test npm test -- --coverage
  docker run -e CI=true pancutan/react-test npm test

after_succes:
  - docker build -t pancutan/multi-client ./client
  - docker build -t pancutan/multi-nginx  ./nginx
  - docker build -t pancutan/multi-server ./server
  - docker build -t pancutan/multi-worker ./worker

  # Subir imagenes a un registry: Dockerhub - para el docker login, las variables de entorno, y
  # para que no se vean publicamente en este repo expuesto en Github, las dejo
  # seteadas en https://travis-ci.org/pancutan/multi-docker/settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push pancutan/multi-client
  - docker push pancutan/multi-nginx
  - docker push pancutan/multi-server
  - docker push pancutan/multi-worker

# Recordar crear un usuario en el IAM, obtener sus lalves allí
# y setearlas en la nube de travis, en https://travis-ci.org/pancutan/multi-docker/settings

# https://www.udemy.com/course/docker-and-kubernetes-the-complete-guide/learn/lecture/11437392#bookmarks
deploy:
    # edge: true # Si aparece missing bucket_name
    provider: elasticbeanstalk
    region: us-west-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-west-2-599651702009
    bucket_path: docker-multi
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: $AWS_SECRET_KEY
